from PySide6.QtGui import QFont

STARTING_TIMER_TIME = 0
STARTING_LAP_TIME = 0
STARTING_GIF_PLAY_TIME = 0
STARTING_LAP = 1
DEFAULT_POMO_TIME = 50 * 60
DEFAULT_BREAK_TIME = 10 * 60

HEADER_FONT = QFont("Arial", 20)
Date